basestation:
  node-type: "base_station"
  IP-address: "10.10.10.100"
  using-radio: "brick-1"
  base-port: "1234"
  clients:
    - "phobos"
    - "dione"

phobos:
  node-type: "ground_robot"
  IP-address: "10.10.10.111"
  using-radio: "deep-blue-3"
  base-port: "3234"
  clients:
    - "basestation"

dione:
  node-type: "aerial_robot"
  IP-address: "10.10.10.106"
  using-radio: "deep-blue-2"
  base-port: "6234"
  clients:
    - "basestation"
